### ISSUE TITLE
Compatibility with InterioEssentials ?

### ISSUE THREAD

**Issue by tchimper** [CreativeDesigner3D/PyClone#12]
Hello, 

First : Awesome plugin, thanks ! 

I'm ready to buy the full package but I have an issue with "Interior Essentials" plugin. 
I've downloaded the installation package with PyClone, installed as described and run as admin.

With a empty project, everything works fine. 
As soon as I include a single element from Interior Essentials though, the following issue is raised when I drop a Home Builder object : 

```
Traceback (most recent call last):
  File "C:\Users\***\Desktop\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\cabinets\cabinet_ops.py", line 288, in modal
    selected_point, selected_obj = pc_utils.get_selection_point(context,event,exclude_objects=self.exclude_objects)
  File "C:\Users\***\Desktop\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\pc_lib\pc_utils.py", line 307, in get_selection_point
    for obj, matrix in visible_objects_and_duplis():
  File "C:\Users\***\Desktop\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\pc_lib\pc_utils.py", line 277, in visible_objects_and_duplis
    obj.dupli_list_create(scene)
AttributeError: 'Object' object has no attribute 'dupli_list_create'

location: <unknown location>:-1
```

If I remove the Interior Essential object, the include works fine again. 

Is there something I miss ? Any incompatibility ?
Thanks in advance !

**Comment by CreativeDesigner3D** [comment]
This error come from trying to place an item in the scene that is linked. I have this fixed in the next version it will be available today.
