### ISSUE TITLE
Deprecated Python API (getchildren)

### ISSUE THREAD

**Issue by BlueMax** [CreativeDesigner3D/PyClone#14]
I get the error below when pressing `Home Builder Library` button. This probably is caused by deprecated Python API (getchildren) that might be still available in bundled Blender/Windows builds. Linux (or Windows) systems running current Python release (3.9.1) might be affected as the function has been removed now.

Reference:  https://docs.python.org/3/whatsnew/3.9.html
> Methods getchildren() and getiterator() of classes ElementTree and Element in the ElementTree module have been removed. They were deprecated in Python 3.2. Use iter(x) or list(x) instead of x.getchildren() and x.iter() or list(x.iter()) instead of x.getiterator().

```
Error: Python: Traceback (most recent call last):
  File "/home/user/.config/blender/2.91/scripts/addons/PyClone/ops/pc_library.py", line 36, in execute
    eval('bpy.ops.' + library.activate_id + '("INVOKE_DEFAULT",library_name=self.library_name)')
  File "<string>", line 1, in <module>
  File "/usr/share/blender/2.91/scripts/modules/bpy/ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/user/.config/blender/2.91/scripts/addons/Library_Home_Builder/home_builder_ops.py", line 60, in execute
    home_builder_pointers.update_pointer_properties()
  File "/home/user/.config/blender/2.91/scripts/addons/Library_Home_Builder/home_builder_pointers.py", line 77, in update_pointer_properties
    pc_pointer_utils.update_props_from_xml_file(get_material_pointer_xml_path(),
  File "/home/user/.config/blender/2.91/scripts/addons/Library_Home_Builder/pc_lib/pc_pointer_utils.py", line 99, in update_props_from_xml_file
    items = elm.getchildren()
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

location: /usr/share/blender/2.91/scripts/modules/bpy/ops.py:130



location: <unknown location>:-1
```

**Comment by BlueMax** [comment]
The main problem (Python 3.9.1) is `Arch Linux` specific. In my opinion its completely wrong to not bundle Python37.

Will keep it open so can see what i've seen. : )
Feel free to close.

**Comment by CreativeDesigner3D** [comment]
I have removed the deprecated getchildren function and replaced it with list(elm.iter())
