### ISSUE TITLE
Arch Linux - Installation of Home Builder Library addon fails

### ISSUE THREAD

**Issue by zauberparacelsus** [CreativeDesigner3D/PyClone#16]
I've compiled a build of PyClone on arch linux, and I am unable to install the home builder or toy box library addons.

Attempting to enable either yields the following errors:
```
Exception in module register(): /home/zauber/.config/blender/2.91/scripts/addons/Library_Home_Builder/__init__.py
Traceback (most recent call last):
  File "/usr/share/blender/2.91/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "/home/zauber/.config/blender/2.91/scripts/addons/Library_Home_Builder/__init__.py", line 56, in register
    load_library_on_file_load()
  File "/home/zauber/.config/blender/2.91/scripts/addons/Library_Home_Builder/__init__.py", line 36, in load_library_on_file_load
    pc_utils.register_library(name="Home Builder Library",
  File "/home/zauber/.config/blender/2.91/scripts/addons/Library_Home_Builder/pc_lib/pc_utils.py", line 350, in register_library
    pyclone = get_wm_props(bpy.context.window_manager)
  File "/home/zauber/.config/blender/2.91/scripts/addons/Library_Home_Builder/pc_lib/pc_utils.py", line 11, in get_wm_props
    return window_manager.pyclone
AttributeError: 'WindowManager' object has no attribute 'pyclone'
```

**Comment by matheusfillipe** [comment]
You no Longer need to compile the pyclone blender fork. Just install the plugin on blender 2.91 and restart blender (at least it was needed to me). Also install pyclone plugin before the libraries.
