### ISSUE TITLE
Activation issue Blender 2.93 Linux

### ISSUE THREAD

**Issue by Sinasta** [CreativeDesigner3D/PyClone#20]
Thanks for your awesome work. I get this error upon activation in Blender 2.93 with python 2.9:

Traceback (most recent call last):
  File "/usr/share/blender/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/sinasta/.config/blender/2.93/scripts/addons/PyClone-master/__init__.py", line 26, in <module>
    from .ops import pc_assembly
  File "/home/sinasta/.config/blender/2.93/scripts/addons/PyClone-master/ops/pc_assembly.py", line 30, in <module>
    from reportlab.pdfgen import canvas
  File "/home/sinasta/.config/blender/2.93/scripts/addons/PyClone-master/python_libs/reportlab/pdfgen/canvas.py", line 19, in <module>
    from reportlab import rl_config
  File "/home/sinasta/.config/blender/2.93/scripts/addons/PyClone-master/python_libs/reportlab/rl_config.py", line 45, in <module>
    _DEFAULTS=_defaults_init()
  File "/home/sinasta/.config/blender/2.93/scripts/addons/PyClone-master/python_libs/reportlab/rl_config.py", line 13, in _defaults_init
    from reportlab.lib.utils import rl_exec
  File "/home/sinasta/.config/blender/2.93/scripts/addons/PyClone-master/python_libs/reportlab/lib/utils.py", line 8, in <module>
    from base64 import decodestring as base64_decodestring, encodestring as base64_encodestring
ImportError: cannot import name 'decodestring' from 'base64' (/usr/lib/python3.9/base64.py)

**Comment by CreativeDesigner3D** [comment]
I'm not very familiar with Linux, but there might be a different installation of the reportlab package that needs to be used for Linux and MacOS. I'll do some research into this, but if there is anyone out there who knows what might be going on please let me know.

**Comment by MaxMorais** [comment]
Hi @CreativeDesigner3D, I expect you are doing fine!

As you can check [here](https://docs.python.org/pt-br/3.7/library/base64.html#base64.decodestring) in Python3 `decodestring, encodestring` have been deprecated in favor of `decodebytes, encodebytes`

So, some alternatives available are ensure compatibility with future versions of python through exception control eg:

```
try:
    from base64 import decodestring as base64_decodestring, encodestring as base64_encodestring
except ImportError: #py > 3.1
    from base64 import decodebytes as base64_decodestring, encodebyes as base64_encodestring
```

Also, I want to contribute with testing on linux environment!
