### ISSUE TITLE
Error enabling Asset Library: Home Builder Library

### ISSUE THREAD

**Issue by msolomon802** [CreativeDesigner3D/PyClone#6]
After enabling the Asset Manager and then going to enable the Home Builder Asset Library I get the following error:
`Traceback (most recent call last):
  File "C:\Users\Documents\Blender\Blender290_1withPyClone\2.90\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\Documents\Blender\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\__init__.py", line 43, in register
    home_builder_props.register()
  File "C:\Users\Documents\Blender\Blender290_1withPyClone\2.90\scripts\modules\bpy\utils\__init__.py", line 714, in register
    register_class(cls)
ValueError: register_class(...): already registered as a subclass 'Pointer''`

**Comment by rambo2002** [comment]
Hello 
i had the same problem. Close Blender and restart it again, then it worked for me

mfg
Joerg
