### ISSUE TITLE
Error in Cabinets creation

### ISSUE THREAD

**Issue by IvailoBurov** [CreativeDesigner3D/PyClone#8]
Hi,
Could not create any cabinet items. Here is the screenshot:

![PyCloneCabinetsErr](https://user-images.githubusercontent.com/63282037/99338126-4ac6b100-288c-11eb-8220-865b5400e17b.jpg)
 
Here are console:
location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\cabinets\cabinet_ops.py", line 293, in modal
    self.confirm_placement(context)
  File "C:\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\cabinets\cabinet_ops.py", line 267, in confirm_placement
    self.cabinet.draw()
  File "C:\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\cabinets\data_cabinets.py", line 246, in draw
    self.carcass.add_insert(self.carcass.exterior)
  File "C:\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\cabinets\data_cabinet_carcass.py", line 444, in add_insert
    insert = self.add_assembly(insert)
  File "C:\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\pc_lib\pc_types.py", line 200, in add_assembly
    assembly.draw()
  File "C:\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\cabinets\data_cabinet_exteriors.py", line 296, in draw
    self.add_door_panel(l_door_container,is_left_door=True)
  File "C:\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\cabinets\data_cabinet_exteriors.py", line 102, in add_door_panel
    pointer = props.cabinet_door_pointers["Base Cabinet Doors"]
KeyError: 'bpy_prop_collection[key]: key "Base Cabinet Doors" not found'

location: <unknown location>:-1

**Comment by Snowdrama** [comment]
@IvailoBurov Hilarious! I just filed the same issue! hahaha #9

**Comment by Snowdrama** [comment]
@IvailoBurov Try restarting and running as administrator, this fixed the issue for me.
![image](https://user-images.githubusercontent.com/1271916/99339561-64e49d00-2854-11eb-9970-4dec294e87a1.png)

**Comment by IvailoBurov** [comment]
Run as administrator does not help. The same errors appears.
One more things: When Home and Toy libraries are activated they does not appears in PyClone Project, so I have to:
1. Deactivate libraries
2. Close Blender (because already registered error appears when trying to activate again)
4. Open Blender.
5. Create a new PyClone project
6. Activate Libraries in Preferences

I have to make this every time. Saving preferences does bot help.

**Comment by IvailoBurov** [comment]
Issue was resolved by following instructions step by step:
[https://creativedesigner3d.com/2020/11/12/installing-blender-with-pyclone-2-90/](url)
