### ISSUE TITLE
Fresh install, bpy_prop_collection "Base Cabinet Door not found"

### ISSUE THREAD

**Issue by Snowdrama** [CreativeDesigner3D/PyClone#9]
Followed the instructions listed here: https://creativedesigner3d.com/2020/11/12/installing-blender-with-pyclone-2-90/

And I got an error when using some of the cabinets

Exact Steps That caused the issue
* Download Zip
* Extract Zip
* Open Blender + PyClone
* Enable Addons
    * PyClone
    * Home Builder Library
    * Toy Box Library 
* Drag Stove, works fine
* Drag Dish Washer, works fine
* Switch to Cabinets
* Drag Base Door Cabinet
* Get "automatic execution" warning, say permanently allow
* Try Dragging again, This Error:
```
Traceback (most recent call last):
  File "D:\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\cabinets\cabinet_ops.py", line 293, in modal
    self.confirm_placement(context)
  File "D:\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\cabinets\cabinet_ops.py", line 267, in confirm_placement
    self.cabinet.draw()
  File "D:\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\cabinets\data_cabinets.py", line 246, in draw
    self.carcass.add_insert(self.carcass.exterior)
  File "D:\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\cabinets\data_cabinet_carcass.py", line 444, in add_insert
    insert = self.add_assembly(insert)
  File "D:\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\pc_lib\pc_types.py", line 200, in add_assembly
    assembly.draw()
  File "D:\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\cabinets\data_cabinet_exteriors.py", line 296, in draw
    self.add_door_panel(l_door_container,is_left_door=True)
  File "D:\Blender290_1withPyClone\2.90\scripts\addons\Library_Home_Builder\cabinets\data_cabinet_exteriors.py", line 102, in add_door_panel
    pointer = props.cabinet_door_pointers["Base Cabinet Doors"]
KeyError: 'bpy_prop_collection[key]: key "Base Cabinet Doors" not found'

location: <unknown location>:-1
```
* Try Walls, works fine
* Try Doors, works fine

Seems to only be cabinets, except one shelf which seems to work correctly. wireframes are left behind from when I get the error
![image](https://user-images.githubusercontent.com/1271916/99338255-d838df80-2851-11eb-989b-cf436d92d3b4.png)

**Comment by Snowdrama** [comment]
Leaving for future reference, this was fixed by running blender as an administrator. Once run with administrator, the cabinets work properly.
![image](https://user-images.githubusercontent.com/1271916/99339490-42528400-2854-11eb-9ea2-951027933c8e.png)
